///
/// @Generated by Mockolo
///

import Combine
import IWOHInteractionKit
@testable import IWOH

final class PostARRepositoryTypMock: PostARRepositoryTyp {
    init() { }
    init(posts: AnyPublisher<[Post], Never>) {
        self._posts = posts
    }

    var postsSetCallCount = 0
    private var _posts: AnyPublisher<[Post], Never>!  { didSet { postsSetCallCount += 1 } }
    var posts: AnyPublisher<[Post], Never> {
        get { return _posts }
        set { _posts = newValue }
    }
}

