///
/// @Generated by Mockolo
///

import Combine
import IWOHInteractionKit
@testable import IWOH

final class UserManagerMock: UserManagerTyp {
    init() { }

	var addCallCount = 0
	var addHandler: ((String) -> ())?
	func add(fcmToken: String)  {
		addCallCount += 1
		if let addHandler = addHandler {
			addHandler(fcmToken)
		}
	}

    var likePostCallCount = 0
    var likePostHandler: ((String) -> (AnyPublisher<Bool, Never>))?
    func likePost(_ postID: String) -> AnyPublisher<Bool, Never> {
        likePostCallCount += 1
        if let likePostHandler = likePostHandler {
            return likePostHandler(postID)
        }
        fatalError("likePostHandler returns can't have a default value thus its handler must be set")
    }

    var addLikeToUserCallCount = 0
    var addLikeToUserHandler: ((String) -> (AnyPublisher<Bool, Never>))?
    func addLikeToUser(_ postID: String) -> AnyPublisher<Bool, Never> {
        addLikeToUserCallCount += 1
        if let addLikeToUserHandler = addLikeToUserHandler {
            return addLikeToUserHandler(postID)
        }
        fatalError("addLikeToUserHandler returns can't have a default value thus its handler must be set")
    }

    var isLikedByUserCallCount = 0
    var isLikedByUserHandler: ((String) -> (AnyPublisher<Bool, Never>))?
    func isLikedByUser(_ postID: String) -> AnyPublisher<Bool, Never> {
        isLikedByUserCallCount += 1
        if let isLikedByUserHandler = isLikedByUserHandler {
            return isLikedByUserHandler(postID)
        }
        fatalError("isLikedByUserHandler returns can't have a default value thus its handler must be set")
    }

    var isCreatedByUserCallCount = 0
    var isCreatedByUserHandler: ((Post) -> (AnyPublisher<Bool, Never>))?
    func isCreatedByUser(_ post: Post) -> AnyPublisher<Bool, Never> {
        isCreatedByUserCallCount += 1
        if let isCreatedByUserHandler = isCreatedByUserHandler {
            return isCreatedByUserHandler(post)
        }
        fatalError("isCreatedByUserHandler returns can't have a default value thus its handler must be set")
    }
}

